### ISSUE TITLE
SqlException (0x80131904): Could not find stored procedure 'dbo.GetCache'

### ISSUE THREAD

**Issue by jhalbrecht** [tjoudeh/eLearning.WebAPI#1]
I've tried running the d196a7e2eb37d49496c4f9d63b46d58f849504dc commit on both visual studio 2012 / 2013 Ultimate. I get this same error. 

Inspection of my SQL server with MSSQL studio reports the eLearning db is created with tables _MigrationHistory, Courses, Enrollments, Students, Subjects and Tutors.

nuGet reports there are 12 available updates.I tried an update all which failed

The YSOD: 

[SqlException (0x80131904): Could not find stored procedure 'dbo.GetCache'.]
   System.Web.Http.WebHost.HttpControllerHandler.EndProcessRequest(IAsyncResult result) +205
   System.Web.Http.WebHost.HttpControllerHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +39
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9690164
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by jhalbrecht** [comment]
Fixed
By creating the stored procedure as outlined in the CacheCow documentation: https://github.com/aliostad/CacheCow/wiki/Getting-started

2) Browse to \packages\CacheCow.Server.EntityTagStore.SqlServer.0.1.0\scripts and use script.sql and run it against your database

Perhaps you could add this step to the wiki, or the github repo entrance readme. I ran the project before reading the part 11 where you outlined this necessary step.

**Comment by tjoudeh** [comment]
You are right, thank you Jeff, I've commented the code in WebAPIconfig file which is responsible to enable cache cow, then added some clear comments on how to activate it and run the SQL scripts needed.
